name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        run: |
          sudo apt-get update; sudo apt-get install make build-essential libssl-dev zlib1g-dev \
          libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
          libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
          mkdir python
          cd python
          wget https://github.com/actions/python-versions/releases/download/3.4.10/python-3.4.10-linux-18.04-x64.tar.gz
          gzip -d -v python-3.4.10-linux-18.04-x64.tar.gz
          tar -xvf python-3.4.10-linux-18.04-x64.tar
          rm -v python-3.4.10-linux-18.04-x64.tar
          chmod +x setup.sh
          ./setup.sh

      - name: Install hugo
        run: brew install hugo

      - name: Build site and minify it
        run: hugo --minify
        
      - name: Deploy to GitHub Pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for the new site to be actualy deployed by Github Pages
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: '30s'

      - name: Save to WayBack Machine
        run: |
          # Install
          git clone https://github.com/agude/wayback-machine-archiver.git
          cd wayback-machine-archiver
          pip install -r requirements.txt
          ./setup.py install
          cd ..
          # Save
          archiver --sitemaps https://greenabg.github.io/gabgvideo/sitemap.xml --archive-sitemap-also --log INFO

